//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALL_TAB_COLS
    {
        public string OWNER { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string DATA_TYPE { get; set; }
        public string DATA_TYPE_MOD { get; set; }
        public string DATA_TYPE_OWNER { get; set; }
        public decimal DATA_LENGTH { get; set; }
        public Nullable<decimal> DATA_PRECISION { get; set; }
        public Nullable<decimal> DATA_SCALE { get; set; }
        public string NULLABLE { get; set; }
        public Nullable<decimal> COLUMN_ID { get; set; }
        public Nullable<decimal> DEFAULT_LENGTH { get; set; }
        public string DATA_DEFAULT { get; set; }
        public Nullable<decimal> NUM_DISTINCT { get; set; }
        public byte[] LOW_VALUE { get; set; }
        public byte[] HIGH_VALUE { get; set; }
        public Nullable<decimal> DENSITY { get; set; }
        public Nullable<decimal> NUM_NULLS { get; set; }
        public Nullable<decimal> NUM_BUCKETS { get; set; }
        public Nullable<System.DateTime> LAST_ANALYZED { get; set; }
        public Nullable<decimal> SAMPLE_SIZE { get; set; }
        public string CHARACTER_SET_NAME { get; set; }
        public Nullable<decimal> CHAR_COL_DECL_LENGTH { get; set; }
        public string GLOBAL_STATS { get; set; }
        public string USER_STATS { get; set; }
        public Nullable<decimal> AVG_COL_LEN { get; set; }
        public Nullable<decimal> CHAR_LENGTH { get; set; }
        public string CHAR_USED { get; set; }
        public string V80_FMT_IMAGE { get; set; }
        public string DATA_UPGRADED { get; set; }
        public string HIDDEN_COLUMN { get; set; }
        public string VIRTUAL_COLUMN { get; set; }
        public Nullable<decimal> SEGMENT_COLUMN_ID { get; set; }
        public decimal INTERNAL_COLUMN_ID { get; set; }
        public string HISTOGRAM { get; set; }
        public string QUALIFIED_COL_NAME { get; set; }
        public string USER_GENERATED { get; set; }
        public string DEFAULT_ON_NULL { get; set; }
        public string IDENTITY_COLUMN { get; set; }
        public string EVALUATION_EDITION { get; set; }
        public string UNUSABLE_BEFORE { get; set; }
        public string UNUSABLE_BEGINNING { get; set; }
    }
}
