//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class B07_STATUS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public B07_STATUS()
        {
            this.D11_UNIT_ACTIVITY = new HashSet<D11_UNIT_ACTIVITY>();
            this.DP_UNIT = new HashSet<DP_UNIT>();
        }
    
        public string B07_STATUS_CODE { get; set; }
        public string B07_DESCRIPTION { get; set; }
        public int B07_COLOR { get; set; }
        public short B07_RESTRICTED { get; set; }
        public short B07_ENABLE { get; set; }
        public int KEY_ID { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D11_UNIT_ACTIVITY> D11_UNIT_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_UNIT> DP_UNIT { get; set; }
    }
}
