//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class C02_ISR_DISPOS
    {
        public string ISR_NO { get; set; }
        public string AGENCY_CODE { get; set; }
        public string DISPOSITION_CODE { get; set; }
        public short C02_SEQUENCE { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual ISR ISR { get; set; }
    }
}
