//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class C06_ISR_COMMENT
    {
        public string ISR_NO { get; set; }
        public string C05_LOGIN_NAME { get; set; }
        public string C05_DATETIME_KEY { get; set; }
        public string C05S_CATEGORY { get; set; }
        public int C05_STAMP { get; set; }
        public short C06_SEQ_NO { get; set; }
        public string C06_COMMENT180 { get; set; }
        public System.DateTimeOffset C06_MOD_DATETIME { get; set; }
    
        public virtual C05_ISR_COMM_HEAD C05_ISR_COMM_HEAD { get; set; }
    }
}
