//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAD_PARAMETERS
    {
        public string AGENCY_CODE { get; set; }
        public string PARAMETER_NAME { get; set; }
        public string PARAMETER_VALUE { get; set; }
        public string PARAMETER_DESC { get; set; }
        public string PARAMETER_MODULE { get; set; }
        public string PARAMETER_TYPE { get; set; }
        public string PARAMETER_TABLE { get; set; }
        public string PARAMETER_IMPACT { get; set; }
        public string PARAMETER_INFO { get; set; }
        public Nullable<short> PARAMETER_LOW { get; set; }
        public Nullable<short> PARAMETER_HIGH { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    }
}
