//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CadEntities : DbContext
    {
        public CadEntities()
            : base("name=CadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ISR> ISRs { get; set; }
        public virtual DbSet<SERVICE_CODE> SERVICE_CODE { get; set; }
        public virtual DbSet<C02_ISR_DISPOS> C02_ISR_DISPOS { get; set; }
        public virtual DbSet<SCREEN2_HEADER> SCREEN2_HEADER { get; set; }
        public virtual DbSet<UDF_CONTAINER> UDF_CONTAINER { get; set; }
        public virtual DbSet<UDF_CONTAINER_NODE> UDF_CONTAINER_NODE { get; set; }
        public virtual DbSet<UDF_NODE_SCREEN_RELATION> UDF_NODE_SCREEN_RELATION { get; set; }
        public virtual DbSet<C07_ISR_ACTIVITY> C07_ISR_ACTIVITY { get; set; }
        public virtual DbSet<B07_STATUS> B07_STATUS { get; set; }
        public virtual DbSet<VTB_CODE> VTB_CODE { get; set; }
        public virtual DbSet<PERSONNEL> PERSONNELs { get; set; }
        public virtual DbSet<S04_SCHED_PERS> S04_SCHED_PERS { get; set; }
        public virtual DbSet<S05_SCHED_EXCEPT> S05_SCHED_EXCEPT { get; set; }
        public virtual DbSet<D11_UNIT_ACTIVITY> D11_UNIT_ACTIVITY { get; set; }
        public virtual DbSet<D16_MEMB_ACTIVITY> D16_MEMB_ACTIVITY { get; set; }
        public virtual DbSet<DP_UNIT> DP_UNIT { get; set; }
        public virtual DbSet<EQUIPMENT> EQUIPMENTs { get; set; }
        public virtual DbSet<S02_SHIFT_DETAIL> S02_SHIFT_DETAIL { get; set; }
        public virtual DbSet<C03_ASSIGN> C03_ASSIGN { get; set; }
        public virtual DbSet<SCREEN2_DETAIL> SCREEN2_DETAIL { get; set; }
        public virtual DbSet<SCREEN2_DETAIL_GRID> SCREEN2_DETAIL_GRID { get; set; }
        public virtual DbSet<SCREEN2_DETAIL_GRID_COLUMN> SCREEN2_DETAIL_GRID_COLUMN { get; set; }
        public virtual DbSet<SCREEN2_DETAIL_GRID_LANGUAGE> SCREEN2_DETAIL_GRID_LANGUAGE { get; set; }
        public virtual DbSet<SCREEN2_FIELD_LANGUAGE> SCREEN2_FIELD_LANGUAGE { get; set; }
        public virtual DbSet<PERSONNEL_SKILL> PERSONNEL_SKILL { get; set; }
        public virtual DbSet<C05_ISR_COMM_HEAD> C05_ISR_COMM_HEAD { get; set; }
        public virtual DbSet<C06_ISR_COMMENT> C06_ISR_COMMENT { get; set; }
        public virtual DbSet<FILE_ATTACHMENT> FILE_ATTACHMENT { get; set; }
        public virtual DbSet<FILE_DEFINITION> FILE_DEFINITION { get; set; }
        public virtual DbSet<ALL_TAB_COLS> ALL_TAB_COLS { get; set; }
        public virtual DbSet<CAD_PARAMETERS> CAD_PARAMETERS { get; set; }
        public virtual DbSet<ISR_UDF> ISR_UDF { get; set; }
    
        public virtual int SP_GETNEXTKEYID_VTBCODEINSERT(string i_TABLENAME, ObjectParameter rETVAL)
        {
            var i_TABLENAMEParameter = i_TABLENAME != null ?
                new ObjectParameter("I_TABLENAME", i_TABLENAME) :
                new ObjectParameter("I_TABLENAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GETNEXTKEYID_VTBCODEINSERT", i_TABLENAMEParameter, rETVAL);
        }
    }
}
