//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class D16_MEMB_ACTIVITY
    {
        public int PERSONNEL_ID { get; set; }
        public string D16_DATETIME_KEY { get; set; }
        public string AGENCY_CODE { get; set; }
        public string UNIT { get; set; }
        public string S02_SHIFT_CODE { get; set; }
        public string SHIFT_DATE { get; set; }
        public string D16S_CAD_ACTION { get; set; }
        public System.DateTimeOffset D16_IN_DATETIME { get; set; }
        public Nullable<System.DateTimeOffset> D16_OUT_DATETIME { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual DP_UNIT DP_UNIT { get; set; }
        public virtual PERSONNEL PERSONNEL { get; set; }
    }
}
