//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPMENT
    {
        public int EQUIP_ID { get; set; }
        public string EQUIP_CODE { get; set; }
        public string EQUIP_DESC { get; set; }
        public string AGENCY_CODE { get; set; }
        public string EQUIP_TYPE { get; set; }
        public string EQUIP_CATEGORY { get; set; }
        public string VALID_FROM_DATE { get; set; }
        public string VALID_TO_DATE { get; set; }
        public Nullable<int> EQUIP_WEIGHT { get; set; }
        public string WEIGHT_UNIT_OF_MEASURE { get; set; }
        public Nullable<int> EQUIP_SIZE { get; set; }
        public string SIZE_UNIT_OF_MEASURE { get; set; }
        public string INVENTORY_NO { get; set; }
        public string EQUIP_COLOR1 { get; set; }
        public string EQUIP_COLOR2 { get; set; }
        public string ESTIMATED_VALUE { get; set; }
        public string PURCHASE_DATE { get; set; }
        public string MANUFACTURER { get; set; }
        public string MANUFACTURER_COUNTRY { get; set; }
        public string EQUIP_MODEL { get; set; }
        public string EQUIP_STYLE { get; set; }
        public string SERIAL_NO { get; set; }
        public Nullable<short> EQUIP_YEAR { get; set; }
        public string WARRANTY_START_DATE { get; set; }
        public string WARRANTY_END_DATE { get; set; }
        public string DEFAULT_STATION { get; set; }
        public string CORPORATE_NO { get; set; }
        public string COMMENTS { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    }
}
