//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ISR()
        {
            this.ISR1 = new HashSet<ISR>();
            this.C02_ISR_DISPOS = new HashSet<C02_ISR_DISPOS>();
            this.C07_ISR_ACTIVITY = new HashSet<C07_ISR_ACTIVITY>();
            this.DP_UNIT = new HashSet<DP_UNIT>();
            this.C03_ASSIGN = new HashSet<C03_ASSIGN>();
            this.C05_ISR_COMM_HEAD = new HashSet<C05_ISR_COMM_HEAD>();
        }
    
        public string ISR_NO { get; set; }
        public string ASSIGN { get; set; }
        public string AGENCY_CODE { get; set; }
        public string DISPATCH_LEVEL { get; set; }
        public Nullable<int> CIVIC_NO { get; set; }
        public string STREET_NAME1 { get; set; }
        public string STREET_NAME2 { get; set; }
        public string P_ARTICLE1 { get; set; }
        public string P_ARTICLE2 { get; set; }
        public string P_DIR1 { get; set; }
        public string P_DIR2 { get; set; }
        public string P_STREET_TYPE1 { get; set; }
        public string P_STREET_TYPE2 { get; set; }
        public string PHONE_NO { get; set; }
        public string ZIP_CODE { get; set; }
        public Nullable<short> HAZMAT { get; set; }
        public Nullable<short> HANDICAP { get; set; }
        public string GEOBASE_COMMENT120 { get; set; }
        public string GEOBASE_SOP { get; set; }
        public string APPT_NO { get; set; }
        public string ALPHA_CIVIC { get; set; }
        public string DISTRICT_NAME { get; set; }
        public string CITY_ABBR { get; set; }
        public string X_STREET1 { get; set; }
        public string X_STREET2 { get; set; }
        public string P_LOC_ENVIRONMENT { get; set; }
        public Nullable<int> GEOBASE_ID { get; set; }
        public string LOCATION_NAME { get; set; }
        public string P_LOC_TYPE { get; set; }
        public string P_PROXIMITY { get; set; }
        public string LEVEL5 { get; set; }
        public string COMPL_ADDRESS { get; set; }
        public string COMPL_CITY_ABBR { get; set; }
        public string COMPL_TEL { get; set; }
        public string P_COMPL_TEL_EXT { get; set; }
        public string COMPL_NAME { get; set; }
        public string COMPL_ADDINFO { get; set; }
        public Nullable<short> COMPL_CONTACT { get; set; }
        public Nullable<short> TAG_FLAG { get; set; }
        public string INIT_SERVICE_CODE { get; set; }
        public string FINAL_SERVICE_CODE { get; set; }
        public string P_ALARM_LEVEL { get; set; }
        public string P_ORIGIN { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public string P_STATUS { get; set; }
        public Nullable<System.DateTimeOffset> STATUS_DATETIME { get; set; }
        public string S_STATUS_NOTE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public string CENTROID { get; set; }
        public Nullable<short> GEOBASE_VALIDATION { get; set; }
        public string GEOBASE_TYPE { get; set; }
        public Nullable<short> EXT_SERVICES { get; set; }
        public string COMMERCIAL_LOCAL { get; set; }
        public string S_MODE { get; set; }
        public Nullable<short> PERSON { get; set; }
        public Nullable<short> EQUIPMENT { get; set; }
        public Nullable<short> RELATION { get; set; }
        public Nullable<short> LOG { get; set; }
        public Nullable<System.DateTimeOffset> LOCK_DATETIME { get; set; }
        public Nullable<System.DateTimeOffset> SCHEDULE_DATETIME { get; set; }
        public Nullable<System.DateTimeOffset> DEFERRED_DATETIME { get; set; }
        public Nullable<short> IS_AN_APPOINTMENT { get; set; }
        public string P_ISR_GROUPING { get; set; }
        public Nullable<short> MOD_LOC { get; set; }
        public Nullable<short> MOD_SERV_CODE { get; set; }
        public Nullable<short> MOD_PRIORITY { get; set; }
        public string OWNER_WORKSTATION { get; set; }
        public string CREA_LOGINNAME { get; set; }
        public Nullable<int> CREA_PERSONNEL_ID { get; set; }
        public string CREA_STATION_NO { get; set; }
        public Nullable<System.DateTimeOffset> CREATED_DATETIME { get; set; }
        public string S_ENTRY_MODE { get; set; }
        public string HANDLING_AGENCY { get; set; }
        public string HANDLING_UNIT { get; set; }
        public Nullable<short> REPORT_COMPLETED { get; set; }
        public Nullable<int> ESTIMATED_TIME { get; set; }
        public Nullable<short> UNIT_COUNT { get; set; }
        public string ALARM_NO { get; set; }
        public string TX_USER { get; set; }
        public string TX_USER_GROUP { get; set; }
        public string TX_STATION { get; set; }
        public string TX_STATION_GROUP { get; set; }
        public string MOD_WORKST_NUMBER { get; set; }
        public string TX_TYPE { get; set; }
        public string PARENT_ISR_NBR { get; set; }
        public string VIEW_GROUP { get; set; }
        public Nullable<System.DateTimeOffset> TX_DATETIME { get; set; }
        public Nullable<System.DateTimeOffset> TIMER_EXP_DATETIME { get; set; }
        public string P_TIMER_EXP_CODE { get; set; }
        public Nullable<short> TIMER_DELAY_TYPE { get; set; }
        public Nullable<decimal> TIMER_DELAY { get; set; }
        public string TIMER_DEST_TYPE { get; set; }
        public string TIMER_DESTINATION { get; set; }
        public Nullable<System.DateTimeOffset> EST_COMPL_DATETIME { get; set; }
        public string EXTERNAL_NO1 { get; set; }
        public string EXTERNAL_NO2 { get; set; }
        public Nullable<System.DateTimeOffset> START_DATETIME { get; set; }
        public Nullable<int> TRAVEL_TIME { get; set; }
        public Nullable<System.DateTimeOffset> START_AFTER_DATETIME { get; set; }
        public string START_DAY_TIME { get; set; }
        public string END_DAY_TIME { get; set; }
        public Nullable<System.DateTimeOffset> END_BEFORE_DATETIME { get; set; }
        public Nullable<short> CUST_PRIORITY { get; set; }
        public Nullable<System.DateTimeOffset> RESTORATION_DATETIME { get; set; }
        public Nullable<short> TASK_TYPE { get; set; }
        public string P_FILTER1 { get; set; }
        public string P_FILTER2 { get; set; }
        public string P_FILTER3 { get; set; }
        public Nullable<short> LONG_CYCLE_JOB { get; set; }
        public short LONG_JOB_FLG { get; set; }
        public Nullable<int> TOTAL_TIME_TO_FIX { get; set; }
        public Nullable<int> AGENCY_SCREEN2_HEADER_ID { get; set; }
        public Nullable<int> SERVICE_CODE_SCREEN2_HEADER_ID { get; set; }
        public Nullable<int> SERVICE_CODE_CONTAINER_ID { get; set; }
        public string MANAGE_PLANNED_DATE_FLG { get; set; }
        public string ALREADY_SEND_FLG { get; set; }
        public short ADJUST_ESTIMATED_TIME_TYPE { get; set; }
        public Nullable<System.DateTimeOffset> EMERGENCY_TIMER_CREATION_DTTM { get; set; }
        public string EMERGENCY_TIMER_FLG { get; set; }
        public string EMERGENCY_TIMER_ACK_FLG { get; set; }
        public Nullable<System.DateTimeOffset> EMERGENCY_TIMER_ACK_DATETIME { get; set; }
        public string TIMEZONE_NAME { get; set; }
        public int KEY_ID { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
        public string SEND_TO_HISTORY_FLG { get; set; }
        public Nullable<System.DateTimeOffset> SEND_TO_HISTORY_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISR> ISR1 { get; set; }
        public virtual ISR ISR2 { get; set; }
        public virtual SERVICE_CODE SERVICE_CODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C02_ISR_DISPOS> C02_ISR_DISPOS { get; set; }
        public virtual SCREEN2_HEADER SCREEN2_HEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C07_ISR_ACTIVITY> C07_ISR_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_UNIT> DP_UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C03_ASSIGN> C03_ASSIGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C05_ISR_COMM_HEAD> C05_ISR_COMM_HEAD { get; set; }
        public virtual ISR_UDF ISR_UDF { get; set; }
    }
}
