//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISR_UDF
    {
        public string ISR_NO { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public string UDF11 { get; set; }
        public string UDF12 { get; set; }
        public string UDF13 { get; set; }
        public Nullable<decimal> UDF14 { get; set; }
        public string UDF15 { get; set; }
        public string UDF16 { get; set; }
        public string UDF17 { get; set; }
        public string UDF18 { get; set; }
        public string UDF19 { get; set; }
        public string UDF20 { get; set; }
        public string UDF21 { get; set; }
        public string UDF22 { get; set; }
        public string UDF23 { get; set; }
        public string UDF24 { get; set; }
        public string UDF25 { get; set; }
        public string UDF26 { get; set; }
        public string UDF27 { get; set; }
        public string UDF28 { get; set; }
        public string UDF29 { get; set; }
        public string UDF30 { get; set; }
        public string UDF31 { get; set; }
        public string UDF32 { get; set; }
        public string UDF33 { get; set; }
        public string UDF34 { get; set; }
        public string UDF35 { get; set; }
        public string UDF36 { get; set; }
        public string UDF37 { get; set; }
        public string UDF38 { get; set; }
        public string UDF39 { get; set; }
        public string UDF40 { get; set; }
        public string UDF41 { get; set; }
        public string UDF42 { get; set; }
        public string UDF43 { get; set; }
        public string UDF44 { get; set; }
        public string UDF45 { get; set; }
        public string UDF46 { get; set; }
        public string UDF47 { get; set; }
        public string UDF48 { get; set; }
        public string UDF49 { get; set; }
        public string UDF50 { get; set; }
        public string UDF51 { get; set; }
        public string UDF52 { get; set; }
        public string UDF53 { get; set; }
        public string UDF54 { get; set; }
        public string UDF55 { get; set; }
        public string UDF56 { get; set; }
        public string UDF57 { get; set; }
        public string UDF58 { get; set; }
        public string UDF59 { get; set; }
        public string UDF60 { get; set; }
        public string UDF61 { get; set; }
        public string UDF62 { get; set; }
        public string UDF63 { get; set; }
        public string UDF64 { get; set; }
        public string UDF65 { get; set; }
        public string UDF66 { get; set; }
        public string UDF67 { get; set; }
        public string UDF68 { get; set; }
        public string UDF69 { get; set; }
        public Nullable<int> UDF70 { get; set; }
        public string UDF71 { get; set; }
        public string UDF72 { get; set; }
        public string UDF73 { get; set; }
        public string UDF74 { get; set; }
        public string UDF75 { get; set; }
        public string UDF76 { get; set; }
        public string UDF77 { get; set; }
        public string UDF78 { get; set; }
        public string UDF79 { get; set; }
        public string UDF80 { get; set; }
        public string UDF81 { get; set; }
        public string UDF82 { get; set; }
        public string UDF83 { get; set; }
        public string UDF84 { get; set; }
        public string UDF85 { get; set; }
        public string UDF86 { get; set; }
        public string UDF87 { get; set; }
        public string UDF88 { get; set; }
        public string UDF89 { get; set; }
        public string UDF90 { get; set; }
        public string UDF91 { get; set; }
        public string UDF92 { get; set; }
        public string UDF93 { get; set; }
        public string UDF94 { get; set; }
        public string UDF95 { get; set; }
        public string UDF96 { get; set; }
        public string UDF97 { get; set; }
        public string UDF98 { get; set; }
        public string UDF99 { get; set; }
        public string UDF100 { get; set; }
        public string UDF101 { get; set; }
        public string UDF102 { get; set; }
        public string UDF103 { get; set; }
        public string UDF104 { get; set; }
        public string UDF105 { get; set; }
        public string UDF106 { get; set; }
        public string UDF107 { get; set; }
        public string UDF108 { get; set; }
        public string UDF109 { get; set; }
        public string UDF110 { get; set; }
        public string UDF111 { get; set; }
        public string UDF112 { get; set; }
        public string UDF113 { get; set; }
        public string UDF114 { get; set; }
        public string UDF115 { get; set; }
        public string UDF116 { get; set; }
        public string UDF117 { get; set; }
        public string UDF118 { get; set; }
        public string UDF119 { get; set; }
        public string UDF120 { get; set; }
        public string UDF121 { get; set; }
        public string UDF122 { get; set; }
        public string UDF123 { get; set; }
        public string UDF124 { get; set; }
        public string UDF125 { get; set; }
        public string UDF126 { get; set; }
        public string UDF127 { get; set; }
        public string UDF128 { get; set; }
        public string UDF129 { get; set; }
        public string UDF130 { get; set; }
        public string UDF131 { get; set; }
        public string UDF132 { get; set; }
        public string UDF133 { get; set; }
        public string UDF134 { get; set; }
        public string UDF135 { get; set; }
        public string UDF136 { get; set; }
        public string UDF137 { get; set; }
        public string UDF138 { get; set; }
        public string UDF139 { get; set; }
        public string UDF140 { get; set; }
        public string UDF141 { get; set; }
        public string UDF142 { get; set; }
        public string UDF143 { get; set; }
        public string UDF144 { get; set; }
        public string UDF145 { get; set; }
        public string UDF146 { get; set; }
        public string UDF147 { get; set; }
        public string UDF148 { get; set; }
        public int CREATION_PERSONNEL_ID { get; set; }
        public string CREATION_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset CREATION_DATETIME { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public string MOD_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual ISR ISR { get; set; }
    }
}
