//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNEL_SKILL
    {
        public int PERSONNEL_ID { get; set; }
        public string P_SKILL { get; set; }
        public string P_DEGRE { get; set; }
        public string EFFECTIVE_DATE { get; set; }
        public string REVISION_DATE { get; set; }
        public string COMMENT120 { get; set; }
        public decimal COMPETENCE_SKILL_LEVEL_PCT { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual PERSONNEL PERSONNEL { get; set; }
    }
}
