//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONNEL()
        {
            this.S04_SCHED_PERS = new HashSet<S04_SCHED_PERS>();
            this.D16_MEMB_ACTIVITY = new HashSet<D16_MEMB_ACTIVITY>();
            this.PERSONNEL_SKILL = new HashSet<PERSONNEL_SKILL>();
        }
    
        public int PERSONNEL_ID { get; set; }
        public string AGENCY_CODE { get; set; }
        public string EMPLOYEE_NO { get; set; }
        public string BADGE_NO { get; set; }
        public string FAMILY_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string ZIP_CODE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public string LONGLAT_REMARK { get; set; }
        public string PHONE_NO1 { get; set; }
        public string PHONE_NO2 { get; set; }
        public string PHONE_NO3 { get; set; }
        public string PHONE_NO4 { get; set; }
        public string P_RANK { get; set; }
        public string P_DEPARTMENT { get; set; }
        public string P_TEAM_SCHED { get; set; }
        public string P_SECURITY_GROUP { get; set; }
        public string TS_TEMPLATE_NAME { get; set; }
        public short ACTIVE { get; set; }
        public string LOGIN_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string DATE_EXPIRED { get; set; }
        public string SLOGIN_NAME { get; set; }
        public string SPASSWORD { get; set; }
        public Nullable<short> PSW_VIOLATED { get; set; }
        public string S_LANGUAGE { get; set; }
        public string COMMENT60 { get; set; }
        public string P_SERVICE { get; set; }
        public string PHOTO_DATE { get; set; }
        public string PHOTO_FILE_NAME { get; set; }
        public string SOC_SEC_NO { get; set; }
        public int ALLOW_DISPOSE { get; set; }
        public string DEFAULT_STATION { get; set; }
        public short DEFAULT_TRUCK_LOC { get; set; }
        public string P_PAY_CODE_REG { get; set; }
        public string P_PAY_CODE_OVER { get; set; }
        public string P_WORK_CODE_REG { get; set; }
        public string P_WORK_CODE_OVER { get; set; }
        public string P_EXC_CODE_REG { get; set; }
        public string P_COST_CODE { get; set; }
        public string ASSIGN_QRY { get; set; }
        public string TRANSFER_QRY { get; set; }
        public string JOB_QRY { get; set; }
        public string CREW_QRY { get; set; }
        public string PAGER_QRY { get; set; }
        public decimal PERS_PERF_FACTOR { get; set; }
        public string P_FILTER1 { get; set; }
        public string P_FILTER2 { get; set; }
        public string P_FILTER3 { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S04_SCHED_PERS> S04_SCHED_PERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<D16_MEMB_ACTIVITY> D16_MEMB_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONNEL_SKILL> PERSONNEL_SKILL { get; set; }
    }
}
