//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class S02_SHIFT_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S02_SHIFT_DETAIL()
        {
            this.DP_UNIT = new HashSet<DP_UNIT>();
        }
    
        public string AGENCY_CODE { get; set; }
        public string S02_SHIFT_CODE { get; set; }
        public string S02_START_TIME { get; set; }
        public decimal S02_DURATION { get; set; }
        public string S02_DESCRIPTION { get; set; }
        public string S02_START_AUTOTS { get; set; }
        public Nullable<decimal> S02_LUNCH_DURATION { get; set; }
        public string S02_LUNCH_START { get; set; }
        public int S02_SHIFT_WORKLOAD { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_UNIT> DP_UNIT { get; set; }
    }
}
