//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class S05_SCHED_EXCEPT
    {
        public int AGENDA_EXCEPTION_ID { get; set; }
        public string AGENCY_CODE { get; set; }
        public string S01_TEAM_SCHED { get; set; }
        public int PERSONNEL_ID { get; set; }
        public string S05P_ACTION { get; set; }
        public Nullable<System.DateTimeOffset> S05_START_DATETIME { get; set; }
        public Nullable<System.DateTimeOffset> S05_END_DATETIME { get; set; }
        public string S02_SHIFT_CODE { get; set; }
        public string S05P_REASON_CODE { get; set; }
        public string S05P_PAY_TYPE { get; set; }
        public string S05P_PAY_CODE { get; set; }
        public string S05_COMMENT { get; set; }
        public string TIMESHEET_PROCESSED_FLG { get; set; }
        public string CREATE_TIMESHEET_FLG { get; set; }
        public Nullable<int> AGENDA_EXCEPTION_BATCH_ID { get; set; }
        public string RECURRENCE_EXCEPTION_FLG { get; set; }
        public Nullable<int> CREATION_PERSONNEL_ID { get; set; }
        public string CREATION_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset CREATION_DATETIME { get; set; }
        public Nullable<int> MOD_PERSONNEL_ID { get; set; }
        public string MOD_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    }
}
