//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN2_DETAIL_GRID
    {
        public int SCREEN2_HEADER_ID { get; set; }
        public int SCREEN2_DETAIL_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string SORT_COLUMN_NAME { get; set; }
        public string SORT_DESCENDING_FLG { get; set; }
        public string ALLOW_DELETE_FLG { get; set; }
        public string CASCADE_DELETE_FLG { get; set; }
        public string SYNC_CHILD_DBLCLICK_FLG { get; set; }
        public int CREATION_PERSONNEL_ID { get; set; }
        public string CREATION_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset CREATION_DATETIME { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public string MOD_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual SCREEN2_DETAIL SCREEN2_DETAIL { get; set; }
    }
}
