//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN2_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCREEN2_HEADER()
        {
            this.ISRs = new HashSet<ISR>();
            this.UDF_NODE_SCREEN_RELATION = new HashSet<UDF_NODE_SCREEN_RELATION>();
            this.SCREEN2_DETAIL = new HashSet<SCREEN2_DETAIL>();
        }
    
        public int SCREEN2_HEADER_ID { get; set; }
        public string SCR_TAG { get; set; }
        public short SCR_TAG_VERSION { get; set; }
        public string TABLE_NAME { get; set; }
        public string ACTIVE_FLG { get; set; }
        public Nullable<int> LABEL_FONT_ID { get; set; }
        public Nullable<int> FIELD_FONT_ID { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISR> ISRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UDF_NODE_SCREEN_RELATION> UDF_NODE_SCREEN_RELATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCREEN2_DETAIL> SCREEN2_DETAIL { get; set; }
    }
}
