//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN2_FIELD_LANGUAGE
    {
        public int SCREEN2_HEADER_ID { get; set; }
        public int SCREEN2_DETAIL_ID { get; set; }
        public string S_LANGUAGE { get; set; }
        public string S_PLATFORM { get; set; }
        public string FIELD_TEXT { get; set; }
        public short LABEL_HEIGHT { get; set; }
        public short LABEL_WIDTH { get; set; }
        public short LABEL_LEFT { get; set; }
        public short LABEL_TOP { get; set; }
        public short FIELD_TOP { get; set; }
        public short FIELD_WIDTH { get; set; }
        public short FIELD_LEFT { get; set; }
        public short FIELD_HEIGHT { get; set; }
        public short DESC_TOP { get; set; }
        public short DESC_WIDTH { get; set; }
        public short DESC_LEFT { get; set; }
        public short DESC_HEIGHT { get; set; }
        public string CBO_CODE_TEXT { get; set; }
        public string CBO_DESC_TEXT { get; set; }
        public short THOUSAND_SEPARATOR { get; set; }
        public short SEQ_ORDER { get; set; }
        public Nullable<int> LABEL_FONT_ID { get; set; }
        public Nullable<int> FIELD_FONT_ID { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual SCREEN2_DETAIL SCREEN2_DETAIL { get; set; }
    }
}
