//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN2_DETAIL_GRID_COLUMN
    {
        public int SCREEN2_HEADER_ID { get; set; }
        public int SCREEN2_DETAIL_ID { get; set; }
        public short COLUMN_SEQUENCE { get; set; }
        public string FIELD_NAME { get; set; }
        public short FIELD_MIN_LENGTH { get; set; }
        public short FIELD_MAX_LENGTH { get; set; }
        public string S_FIELD_TYPE { get; set; }
        public string UID_TYPE { get; set; }
        public short NBR_DECIMAL { get; set; }
        public string PARENT_FIELD_NAME { get; set; }
        public string CONTROL_TYPE { get; set; }
        public string FORMAT { get; set; }
        public short EDITABLE { get; set; }
        public Nullable<short> VISIBLE { get; set; }
        public Nullable<short> KEY_COLUMN { get; set; }
        public short FORCED { get; set; }
        public string CBO_SQL_CODE { get; set; }
        public string AUTO_SEQ_FLG { get; set; }
        public string GROUP_BY_FLG { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string IMPORT_FIELD { get; set; }
        public string DUPLICATE_ACTION { get; set; }
        public string COMBO_VALIDATION_FLG { get; set; }
        public int CREATION_PERSONNEL_ID { get; set; }
        public string CREATION_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset CREATION_DATETIME { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public string MOD_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
        public string HOST_INQ_LINK_FLG { get; set; }
    
        public virtual SCREEN2_DETAIL SCREEN2_DETAIL { get; set; }
    }
}
