//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCREEN2_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCREEN2_DETAIL()
        {
            this.SCREEN2_DETAIL_GRID_COLUMN = new HashSet<SCREEN2_DETAIL_GRID_COLUMN>();
            this.SCREEN2_DETAIL_GRID_LANGUAGE = new HashSet<SCREEN2_DETAIL_GRID_LANGUAGE>();
            this.SCREEN2_FIELD_LANGUAGE = new HashSet<SCREEN2_FIELD_LANGUAGE>();
        }
    
        public int SCREEN2_HEADER_ID { get; set; }
        public int SCREEN2_DETAIL_ID { get; set; }
        public string FIELD_NAME { get; set; }
        public short FIELD_MIN_LENGTH { get; set; }
        public short FIELD_MAX_LENGTH { get; set; }
        public string S_FIELD_TYPE { get; set; }
        public string FIELD_CONTROL_TYPE { get; set; }
        public string PARENT_TAG { get; set; }
        public string CONTROL_TAG { get; set; }
        public short INVISIBLE { get; set; }
        public short VALIDATION { get; set; }
        public short FORCED { get; set; }
        public short MODIFIABLE { get; set; }
        public short MODIFIABLE_INSERT { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string CBO_CODE_TAG { get; set; }
        public string CBO_DESC_TAG { get; set; }
        public string CBO_SQL_CODE { get; set; }
        public string AUTO_SEQ_FLG { get; set; }
        public string VALIDATION_FORMULA { get; set; }
        public string IMPORT_FIELD { get; set; }
        public short IMPORT_CAD_AGENT { get; set; }
        public short NBR_DECIMAL { get; set; }
        public string GUI_FORMULA_VALIDATION_FLG { get; set; }
        public string DUPLICATE_ACTION { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual SCREEN2_DETAIL_GRID SCREEN2_DETAIL_GRID { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCREEN2_DETAIL_GRID_COLUMN> SCREEN2_DETAIL_GRID_COLUMN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCREEN2_DETAIL_GRID_LANGUAGE> SCREEN2_DETAIL_GRID_LANGUAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCREEN2_FIELD_LANGUAGE> SCREEN2_FIELD_LANGUAGE { get; set; }
        public virtual SCREEN2_HEADER SCREEN2_HEADER { get; set; }
    }
}
