//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE_CODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICE_CODE()
        {
            this.ISRs = new HashSet<ISR>();
            this.DP_UNIT = new HashSet<DP_UNIT>();
        }
    
        public string AGENCY_CODE { get; set; }
        public string SERVICE_CODE1 { get; set; }
        public string DESCRIPTION { get; set; }
        public string LONG_DESCRIPTION { get; set; }
        public short PRIORITY { get; set; }
        public string DEFAULT_DISP_CODE { get; set; }
        public string T11_PLAN_TITLE { get; set; }
        public string SOP_FILE_NAME { get; set; }
        public string P_TAG { get; set; }
        public Nullable<short> RUNCARD { get; set; }
        public Nullable<short> UNIT_AVAILABLE { get; set; }
        public Nullable<short> ADMIN_CODE { get; set; }
        public Nullable<short> REPORT_REQUIRED { get; set; }
        public Nullable<short> RECALL { get; set; }
        public Nullable<short> BREAK_BY_LUNCH { get; set; }
        public string COMMENT120 { get; set; }
        public int ESTIMATED_TIME { get; set; }
        public string ISR_TABLE_NAME { get; set; }
        public string ISR_CONTAINER_NAME { get; set; }
        public string RPT_TABLE_NAME { get; set; }
        public string REPORT_CONTAINER_NAME { get; set; }
        public string BIGADD_TEMPLATE_NAME1 { get; set; }
        public string BIGADD_TEMPLATE_NAME2 { get; set; }
        public string B10_PICKLIST_ISR { get; set; }
        public string B10_PICKLIST_RPT { get; set; }
        public short FORCE_APPROVAL { get; set; }
        public short MOBILE_DETAIL { get; set; }
        public short RESPECT_SHIFT { get; set; }
        public short AUTO_DISPOSE_LAN { get; set; }
        public short AUTO_DISPOSE_MOB { get; set; }
        public short LONG_CYCLE_JOB { get; set; }
        public short SAME_CREW { get; set; }
        public Nullable<short> RECURRENCE_PATTERN { get; set; }
        public Nullable<short> RECURRENCE_SEQUENCE { get; set; }
        public Nullable<int> TOTAL_TIME_TO_FIX { get; set; }
        public short SINGLE_JOB { get; set; }
        public short COMPLEX_JOB { get; set; }
        public short SUB_JOB { get; set; }
        public string SCHED_TIME_PERIOD_CODE { get; set; }
        public short AM_TIME_PERIOD_FLG { get; set; }
        public short PM_TIME_PERIOD_FLG { get; set; }
        public short EVE_TIME_PERIOD_FLG { get; set; }
        public Nullable<decimal> RECMD_SEARCH_RADIUS { get; set; }
        public string RECMD_SEARCH_RADIUS_UOM { get; set; }
        public short ALLOW_OVERTIME_FLG { get; set; }
        public short LOCK_IN_UPDATE { get; set; }
        public short WEEK_DAY1 { get; set; }
        public short WEEK_DAY2 { get; set; }
        public short WEEK_DAY3 { get; set; }
        public short WEEK_DAY4 { get; set; }
        public short WEEK_DAY5 { get; set; }
        public short WEEK_DAY6 { get; set; }
        public short WEEK_DAY7 { get; set; }
        public short USE_AGENCY_TRIGGER { get; set; }
        public string ADDITIONNAL_ACTION { get; set; }
        public string SKYVIEW_BITMAP_KEY { get; set; }
        public string P_FILTER1 { get; set; }
        public string P_FILTER2 { get; set; }
        public string P_FILTER3 { get; set; }
        public short LONG_JOB_FLG { get; set; }
        public int MINIMUM_ASSIGN_MINUTE { get; set; }
        public short MINIMUM_NBR_CREW_REQUIRED { get; set; }
        public short MAXIMUM_NBR_CREW_REQUIRED { get; set; }
        public short MINIMUM_CREW_MEMBER_COUNT { get; set; }
        public string SEND_TO_HISTORY_MODE { get; set; }
        public short ADJUST_ESTIMATED_TIME_TYPE { get; set; }
        public short MANUAL_ASSIGN_SKILL_VALID_FLG { get; set; }
        public short MANUAL_ASSIGN_EQUIP_VALID_FLG { get; set; }
        public short MANUAL_ASSIGN_MAT_VALID_FLG { get; set; }
        public string DUP_AGENCY_TEMPLATE_FLG { get; set; }
        public string DUP_JOB_TYPE_TEMPLATE_FLG { get; set; }
        public string PERMIT_LONG_JOB_ADJ_FLG { get; set; }
        public Nullable<int> STATUS_GROUP_ID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public int KEY_ID { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISR> ISRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_UNIT> DP_UNIT { get; set; }
    }
}
