//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDF_CONTAINER_NODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UDF_CONTAINER_NODE()
        {
            this.UDF_NODE_SCREEN_RELATION = new HashSet<UDF_NODE_SCREEN_RELATION>();
        }
    
        public int CONTAINER_ID { get; set; }
        public int NODE_ID { get; set; }
        public Nullable<int> PARENT_NODE_ID { get; set; }
        public short NODE_SEQUENCE { get; set; }
        public string NODE_NAME { get; set; }
        public short NODE_TYPE { get; set; }
        public string REFERENCE_TABLE_NAME { get; set; }
        public string REFERENCE_TABLE_KEY { get; set; }
        public string CONDITION_CLAUSE { get; set; }
        public Nullable<int> BG_COLOR { get; set; }
        public Nullable<int> FG_COLOR { get; set; }
        public string NODE_BMP_FILE_NAME { get; set; }
        public string DISPLAY_UNDER_SUBNODE_FLG { get; set; }
        public string DISPLAY_ON_DATA_FLG { get; set; }
        public string ALLOW_ADD_FLG { get; set; }
        public string ALLOW_DELETE_FLG { get; set; }
        public string DYN_SUBNODE_TITLE { get; set; }
        public Nullable<int> DYN_SUBNODE_BG_COLOR { get; set; }
        public Nullable<int> DYN_SUBNODE_FG_COLOR { get; set; }
        public string DYN_SUBNODE_BMP_FILE_NAME { get; set; }
        public string PLUGINNAME { get; set; }
        public string DYN_SUBNODE_PLUGINNAME { get; set; }
        public int CREATION_PERSONNEL_ID { get; set; }
        public string CREATION_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset CREATION_DATETIME { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public string MOD_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual UDF_CONTAINER UDF_CONTAINER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UDF_NODE_SCREEN_RELATION> UDF_NODE_SCREEN_RELATION { get; set; }
    }
}
