//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDF_NODE_SCREEN_RELATION
    {
        public int NODE_SCREEN_RELATION_ID { get; set; }
        public int CONTAINER_ID { get; set; }
        public int NODE_ID { get; set; }
        public string SUBNODE_TEMPLATE_FLG { get; set; }
        public short TEMPLATE_SEQUENCE { get; set; }
        public int TEMPLATE_SCREEN_HEADER_ID { get; set; }
        public string VALIDATE_AT_STATUS { get; set; }
        public string REQUIRED_AT_STATUS { get; set; }
        public int CREATION_PERSONNEL_ID { get; set; }
        public string CREATION_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset CREATION_DATETIME { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public string MOD_PERSONNEL_NAME { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    
        public virtual UDF_CONTAINER_NODE UDF_CONTAINER_NODE { get; set; }
        public virtual SCREEN2_HEADER SCREEN2_HEADER { get; set; }
    }
}
