//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cad.DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class VTB_CODE
    {
        public string VTB_NAME { get; set; }
        public string VTB_CODE1 { get; set; }
        public string PARENT_VTB_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public short RESTRICTED { get; set; }
        public string REFERENCE1 { get; set; }
        public string REFERENCE2 { get; set; }
        public string REFERENCE3 { get; set; }
        public string REFERENCE4 { get; set; }
        public string SORT_SEQUENCE { get; set; }
        public int KEY_ID { get; set; }
        public int MOD_PERSONNEL_ID { get; set; }
        public System.DateTimeOffset MOD_DATETIME { get; set; }
    }
}
